[2022-08-17 19:59:00,835] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Deepface.validate manual__2022-08-17T19:58:56.207740+00:00 [queued]>
[2022-08-17 19:59:01,130] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Deepface.validate manual__2022-08-17T19:58:56.207740+00:00 [queued]>
[2022-08-17 19:59:01,130] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 19:59:01,130] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-08-17 19:59:01,130] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 19:59:01,161] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): validate> on 2022-08-17 19:58:56.207740+00:00
[2022-08-17 19:59:01,170] {standard_task_runner.py:52} INFO - Started process 3524 to run task
[2022-08-17 19:59:01,175] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Deepface', 'validate', 'manual__2022-08-17T19:58:56.207740+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/deepface.py', '--cfg-path', '/tmp/tmpt3jtzj9k', '--error-file', '/tmp/tmpyfjs20ly']
[2022-08-17 19:59:01,176] {standard_task_runner.py:80} INFO - Job 60: Subtask validate
[2022-08-17 19:59:01,250] {task_command.py:370} INFO - Running <TaskInstance: Deepface.validate manual__2022-08-17T19:58:56.207740+00:00 [running]> on host d254c144b912
[2022-08-17 19:59:01,379] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Deepface
AIRFLOW_CTX_TASK_ID=validate
AIRFLOW_CTX_EXECUTION_DATE=2022-08-17T19:58:56.207740+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-17T19:58:56.207740+00:00
[2022-08-17 19:59:09,058] {logging_mixin.py:115} INFO - 1/1 [==============================] - ETA: 0s
[2022-08-17 19:59:09,058] {logging_mixin.py:115} INFO - 1/1 [==============================] - 1s 681ms/step
[2022-08-17 19:59:09,449] {logging_mixin.py:115} INFO - 1/1 [==============================] - ETA: 0s
[2022-08-17 19:59:09,450] {logging_mixin.py:115} INFO - 1/1 [==============================] - 0s 278ms/step
[2022-08-17 19:59:12,181] {logging_mixin.py:115} INFO - 1/1 [==============================] - ETA: 0s
[2022-08-17 19:59:12,181] {logging_mixin.py:115} INFO - 1/1 [==============================] - 0s 322ms/step
[2022-08-17 19:59:12,974] {logging_mixin.py:115} INFO - 1/1 [==============================] - ETA: 0s
[2022-08-17 19:59:12,975] {logging_mixin.py:115} INFO - 1/1 [==============================] - 0s 406ms/step
[2022-08-17 19:59:15,010] {logging_mixin.py:115} INFO - Email sent successfully!
[2022-08-17 19:59:15,012] {python.py:173} INFO - Done. Returned value was: None
[2022-08-17 19:59:15,091] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Deepface, task_id=validate, execution_date=20220817T195856, start_date=20220817T195900, end_date=20220817T195915
[2022-08-17 19:59:15,204] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-17 19:59:15,233] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
