[2022-08-17 20:02:02,890] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Deepface.validate manual__2022-08-17T20:01:57.815022+00:00 [queued]>
[2022-08-17 20:02:03,128] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Deepface.validate manual__2022-08-17T20:01:57.815022+00:00 [queued]>
[2022-08-17 20:02:03,128] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 20:02:03,128] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-08-17 20:02:03,128] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-17 20:02:03,150] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): validate> on 2022-08-17 20:01:57.815022+00:00
[2022-08-17 20:02:03,162] {standard_task_runner.py:52} INFO - Started process 3713 to run task
[2022-08-17 20:02:03,167] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Deepface', 'validate', 'manual__2022-08-17T20:01:57.815022+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/deepface.py', '--cfg-path', '/tmp/tmp0ngdgnwj', '--error-file', '/tmp/tmpt_mw8ipc']
[2022-08-17 20:02:03,169] {standard_task_runner.py:80} INFO - Job 61: Subtask validate
[2022-08-17 20:02:03,243] {task_command.py:370} INFO - Running <TaskInstance: Deepface.validate manual__2022-08-17T20:01:57.815022+00:00 [running]> on host d254c144b912
[2022-08-17 20:02:03,345] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=Deepface
AIRFLOW_CTX_TASK_ID=validate
AIRFLOW_CTX_EXECUTION_DATE=2022-08-17T20:01:57.815022+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-17T20:01:57.815022+00:00
[2022-08-17 20:02:10,576] {logging_mixin.py:115} INFO - 1/1 [==============================] - ETA: 0s
[2022-08-17 20:02:10,576] {logging_mixin.py:115} INFO - 1/1 [==============================] - 1s 579ms/step
[2022-08-17 20:02:11,001] {logging_mixin.py:115} INFO - 1/1 [==============================] - ETA: 0s
[2022-08-17 20:02:11,001] {logging_mixin.py:115} INFO - 1/1 [==============================] - 0s 329ms/step
[2022-08-17 20:02:14,001] {logging_mixin.py:115} INFO - 1/1 [==============================] - ETA: 0s
[2022-08-17 20:02:14,001] {logging_mixin.py:115} INFO - 1/1 [==============================] - 0s 403ms/step
[2022-08-17 20:02:14,605] {logging_mixin.py:115} INFO - 1/1 [==============================] - ETA: 0s
[2022-08-17 20:02:14,606] {logging_mixin.py:115} INFO - 1/1 [==============================] - 0s 329ms/step
[2022-08-17 20:02:16,549] {logging_mixin.py:115} INFO - Email sent successfully!
[2022-08-17 20:02:18,873] {logging_mixin.py:115} INFO - Email sent successfully!
[2022-08-17 20:02:18,876] {python.py:173} INFO - Done. Returned value was: None
[2022-08-17 20:02:18,915] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=Deepface, task_id=validate, execution_date=20220817T200157, start_date=20220817T200202, end_date=20220817T200218
[2022-08-17 20:02:19,080] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-17 20:02:19,120] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
